config/routes.rb
Anonymail::Application.routes.draw do

  root 'demo#index'

  resource :demo

  namespace :users do
    
    resources :dashboard, :only => [:index]
    resources :mail

  end

  namespace :api do

    namespace :mail do
  
    resources :reports
    resources :account, :only => [:index]
    resources :tokens, :only => [:create, :destroy]
#    resources :mail, :only => [:create]
    resources :mailbox
    resources :entry, :only => [:create, :show]
    devise_for :user, :module => "devise", :controllers => { :sessions => "api/mail/sessions", :registrations => "api/mail/registrations" }

    resources :users do
    end

    end

  end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout "demo"

  def index
  end

end

app/helpers/demo_helper.rb
module DemoHelper

  def auth_token
    cookies["auth_token"]
  end

end

app/views/demo/index.html.haml
#console.col-md-12

.row

  .col-md-8
    %h2 Sign-up Example
    = form_tag api_mail_user_registration_path(:format => :json), :class => "col-md-8 registration-form", :remote => true, :method => :post do

      .devise-registration-form.form-inputs
        .row
          .col-md-4
            = label_tag "Email Address"
          .col-md-4
            = text_field_tag "user[email]"
        .row
          .col-md-4
            = label_tag "Password"
          .col-md-4
            = password_field_tag "user[password]"
        .row
          .col-md-4
            = label_tag "Password Confirmation"
          .col-md-4
            = password_field_tag "user[password_confirmation]"
        .row
          .form-actions.col-md-8
            %button.btn.btn-success Sign up

  .col-md-8
    %h2 Login Example
    = form_tag api_mail_tokens_path(:format => :json), :class => "col-md-8 log demo-login-form log", :remote => true do
      .row
        .col-md-4
          = label_tag "Email"
        .col-md-4
          = text_field_tag 'user[email]'
      .row
        .col-md-4
          = label_tag "Password"
        .col-md-4
          = password_field_tag 'user[password]'
      .row
        .col-md-8
      %button.btn.btn-primary Sign in

  .col-md-4
    %h2 Token
    #token
      = auth_token

.row
  .col-md-8
    %h2 Check Account Details
    = form_tag "/api/mail/account.json", :class => "col-md-8 demo-account-form", :method => :get, :remote => true do
      = hidden_field_tag "auth_token", auth_token, :class => "auth-token-input"
      %button.btn.btn-primary Get My Account Details
  .col-md-4
    .col-md-4#account

.row
  .col-md-4
    %h2 Mailbox
    = form_tag "/api/mail/mailbox.json", :class => "col-md-8 log mailbox-form log", :method => :get, :remote => true do
      .row
        .col-md-3
          = label_tag "Page"
        .col-md-1
          = text_field_tag 'page'
          = hidden_field_tag "auth_token", auth_token, :class => "auth-token-input"
      .row
        .col-md-4
          %button.btn.btn-primary Get Mail
  .col-md-8
    .col-md-8#mailbox