config/routes.rb
Anonymail::Application.routes.draw do

  root 'demo#index'

  resource :demo

  namespace :users do
    
    resources :dashboard, :only => [:index]
    resources :mail

  end

  namespace :api do

    namespace :mail do
  
    resources :reports
    resources :account, :only => [:index]
    resources :tokens, :only => [:create, :destroy]
#    resources :mail, :only => [:create]
    resources :mailbox
    resources :entry, :only => [:create, :show]
    devise_for :user, :module => "devise", :controllers => { :sessions => "api/mail/sessions", :registrations => "api/mail/registrations" }

    resources :users do
    end

    end

  end

end

app/views/shared/_login.html.haml
= form_tag api_user_session_path, :class => "homepage-login-form" do
  .row.form-row
    .col-md-3
      = label_tag "Email"
    .col-md-3
      = text_field_tag 'user[email]'
  .row.form-row
    .col-md-3
      = label_tag "Password"
    .col-md-3
      = password_field_tag 'user[password]'
  .row.form-row
    .col-md-3
    = label_tag 'user[remember_me]', 'Remember me'
    .col-md-2
      = check_box_tag 'user[remember_me]'
  .row.form-row
    .col-md-5
      %button.btn.btn-primary Sign in
  .row.form-row
    = link_to "Forgot your password?", api_new_password_path('user')

app/views/shared/_navbar_login.html.haml
= form_tag api_user_session_path, :class => "homepage-login-form form-inline" do
  = label_tag "Email"
  = text_field_tag 'user[email]'
  = label_tag "Password"
  = password_field_tag 'user[password]'
  = label_tag 'user[remember_me]', 'Remember me'
  = check_box_tag 'user[remember_me]'
  %button.btn.btn-primary Sign in
  = link_to "Forgot your password?", new_api_user_password_path('user')

app/views/shared/_sidebar.html.haml
%ul.navigation-bar
  %li
    %span.glyphicon.glyphicon-envelope
    Mailbox
  %li Option 2
  %li Option 3